
package fr.dawan.projsoap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculette", targetNamespace = "http://ws.projsoap.dawan.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculette {


    /**
     * 
     * @param a
     * @param b
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "resultat", targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.AdditionResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/Calculette/additionRequest", output = "http://ws.projsoap.dawan.fr/Calculette/additionResponse")
    public int addition(
        @WebParam(name = "a", targetNamespace = "")
        int a,
        @WebParam(name = "b", targetNamespace = "")
        int b);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "soustraction", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.Soustraction")
    @ResponseWrapper(localName = "soustractionResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.SoustractionResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/Calculette/soustractionRequest", output = "http://ws.projsoap.dawan.fr/Calculette/soustractionResponse")
    public int soustraction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
