
package fr.dawan.projsoap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContactWS", targetNamespace = "http://ws.projsoap.dawan.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContactWS {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "resultat", targetNamespace = "")
    @RequestWrapper(localName = "remove", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.RemoveResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/ContactWS/removeRequest", output = "http://ws.projsoap.dawan.fr/ContactWS/removeResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.projsoap.dawan.fr/ContactWS/remove/Fault/Exception")
    })
    public String remove(
        @WebParam(name = "id", targetNamespace = "")
        long id)
        throws Exception_Exception
    ;

    /**
     * 
     * @param contact
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultat", targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.UpdateResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/ContactWS/updateRequest", output = "http://ws.projsoap.dawan.fr/ContactWS/updateResponse")
    public String update(
        @WebParam(name = "contact", targetNamespace = "")
        Contact contact);

    /**
     * 
     * @param contact
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultat", targetNamespace = "")
    @RequestWrapper(localName = "insert", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.InsertResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/ContactWS/insertRequest", output = "http://ws.projsoap.dawan.fr/ContactWS/insertResponse")
    public String insert(
        @WebParam(name = "contact", targetNamespace = "")
        Contact contact);

    /**
     * 
     * @return
     *     returns java.util.List<fr.dawan.projsoap.ws.Contact>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.FindAllResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/ContactWS/findAllRequest", output = "http://ws.projsoap.dawan.fr/ContactWS/findAllResponse")
    public List<Contact> findAll();

    /**
     * 
     * @return
     *     returns java.util.List<fr.dawan.projsoap.ws.Contact>
     */
    @WebMethod
    @WebResult(name = "liste-contact", targetNamespace = "")
    @RequestWrapper(localName = "findAllXml", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.FindAllXml")
    @ResponseWrapper(localName = "findAllXmlResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.FindAllXmlResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/ContactWS/findAllXmlRequest", output = "http://ws.projsoap.dawan.fr/ContactWS/findAllXmlResponse")
    public List<Contact> findAllXml();

    /**
     * 
     * @param id
     * @return
     *     returns fr.dawan.projsoap.ws.Contact
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "contact", targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://ws.projsoap.dawan.fr/", className = "fr.dawan.projsoap.ws.FindByIdResponse")
    @Action(input = "http://ws.projsoap.dawan.fr/ContactWS/findByIdRequest", output = "http://ws.projsoap.dawan.fr/ContactWS/findByIdResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://ws.projsoap.dawan.fr/ContactWS/findById/Fault/Exception")
    })
    public Contact findById(
        @WebParam(name = "id", targetNamespace = "")
        long id)
        throws Exception_Exception
    ;

}
